name: Bug Report
description: Found a problem? Tell us so we can fix it!
title: "[Bug] <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to help improve melonDS DS!
        Please answer the following questions to the best of your ability.

  - type: input
    id: version
    attributes:
      label: What version of melonDS DS are you using?
      description: >
        Different frontends have their own ways of showing this info.
        In RetroArch, check the lower-left corner of the screen
        when paused while the core is loaded.
      placeholder: 1.0.1
    validations:
      required: true

  - type: dropdown
    id: upstream
    attributes:
      label: Does the problem happen in upstream melonDS?
      description: >
        This core stays close to upstream melonDS,
        so any bugs present there may affect melonDS DS as well.
        
        **If the answer is yes, please [open a ticket or find an existing one](https://github.com/melonDS-emu/melonDS/issues)
        in the upstream melonDS repository.**
        You may continue to submit this one,
        but it may be closed if there's nothing I can do about it in this repo.
      options:
        - I don't know.
        - Yes, in the [latest stable release](https://github.com/melonDS-emu/melonDS/releases).
        - Yes, in the [latest `master` build](https://github.com/melonDS-emu/melonDS).
        - No, it's a bug specific to melonDS DS.
        - Not applicable, the bug involves features not present in upstream melonDS.
      default: 0
    validations:
      required: true

  - type: textarea
    id: observed
    attributes:
      label: What happened?
      description: >
        Describe the problem you're having,
        and provide as much information as you can to help us reproduce it.
        Please attach logs, screenshots, videos, savestates, or save data
        (otherwise you may be asked to go back and take some).

        **Include steps to reproduce the problem if possible;**
        bugs that are easy to reproduce are much easier to fix!
      placeholder: >
        Waluigi is in my computer! Here's a log:
        ```
        [  0.000000] [FATAL] Waluigi is in your computer!
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should've happened instead?
      description: >
        Please describe what you expected to happen.
        If possible, a screenshot of the expected behavior
        in upstream [melonDS](https://melonds.kuribo64.net)
        or another emulator would be helpful.
      placeholder: >
        Waluigi should not be in my computer!
        His constant screaming is making the emulator unusable.
    validations:
      required: true

  - type: checkboxes
    id: platform
    attributes:
      label: Which platforms do you see the problem on?
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: Other (specify below)
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: Which versions of the OS?
      description: Name the version (and other configuration info) of the OS you've reproduced the issue on.
      placeholder: Windows 11 21H2, macOS 14 (Apple Silicon), Ubuntu 21.04 (x86_64), etc.
    validations:
      required: true

  - type: input
    id: frontend
    attributes:
      label: Which libretro frontend are you using?
      description: >
        melonDS DS is primarily designed for RetroArch,
        but it will work on other libretro frontends as well.
        Tell me which frontend(s) you've seen the problem on,
        as well as the version and distribution.
      placeholder: RetroArch 1.16.0, Steam and Flatpak releases
    validations:
        required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: >
        You must understand and agree to the following terms in order to submit this bug report.
        If your behavior indicates otherwise, your report may be closed.
      options:
        - label: I agree to follow the [code of conduct](../CODE_OF_CONDUCT.md).
          required: true
        - label: I understand that melonDS DS is not developed or maintained by the authors of melonDS.
          required: true
        - label: >
            I understand that the author develops this core in his spare time,
            and that he is under no obligation to respond to this bug report.
          required: true

  - type: markdown
    attributes:
      value: All good? Thank you very much!