name: Install Dependencies
description: Install Dependencies
inputs:
  build-dir:
    description: The directory in which to build the project.
    required: true
  ccache:
    description: CCache variant
    required: false
    default: ccache
  ccache-cache-name:
    description: CCache cache name
    required: true
  runs-on:
    description: The platform on which the workflow will be run.
    required: true
runs:
  using: composite
  steps:
    - name: Install GCC Problem Matcher
      uses: root-project/gcc-problem-matcher-improved@9d83f12b27a78210f0485fb188e08d94fa807a6d
      if: ${{ !contains(inputs.runs-on, 'windows') }} # See https://github.com/root-project/gcc-problem-matcher-improved/issues/3
      with:
        build-directory: ${{ inputs.build-dir }}

    - name: Install MSYS2 Dependencies (Windows)
      uses: msys2/setup-msys2@v2
      if: ${{ contains(inputs.runs-on, 'windows') }}
      with:
        msystem: MINGW64
        update: true
        install: git pkgconf mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-sccache

    - name: Install Dependencies (macOS)
      if: ${{ contains(inputs.runs-on, 'macos') }}
      shell: bash
      run: brew install pkg-config cmake ninja ccache

    - name: Install Dependencies (Linux x86_64)
      if: ${{ contains(inputs.runs-on, 'ubuntu') && !contains(inputs.ccache-cache-name, 'aarch64') }}
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake ninja-build libepoxy-dev ccache
        version: 1.0

    - name: Install Repositories (Linux aarch64)
      if: ${{ contains(inputs.runs-on, 'ubuntu') && contains(inputs.ccache-cache-name, 'aarch64') }}
      shell: bash
      run: |
        sudo dpkg --add-architecture arm64
        sudo sh -c "sed \"s|^deb \([a-z\.:/]*\) \([a-z\-]*\) \(.*\)$|deb [arch=amd64] \1 \2 \3\ndeb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports \2 \3|\" /etc/apt/sources.list > /etc/apt/sources.list.new"
        sudo rm /etc/apt/sources.list
        sudo mv /etc/apt/sources.list{.new,}
        sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-suggests {gcc-10,g++-10,pkg-config}-aarch64-linux-gnu libepoxy-dev:arm64 zlib1g-dev:arm64 cmake dpkg-dev

    - name: Set Up CCache
      uses: hendrikmuhs/ccache-action@v1.2.9
      with:
        key: ${{ inputs.ccache-cache-name }}
        variant: ${{ inputs.ccache }}