name: Install Dependencies (Windows)
description: Install dependencies for building on Windows.
inputs:
  archive-name:
    description: The name of the archive to upload.
    required: true

runs:
  using: composite
  steps:
    - name: Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git pkgconf mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-ninja mingw-w64-x86_64-toolchain