name: Build Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  windows:
    name: Windows (x86_64)
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check Out Source
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git pkgconf mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-ninja mingw-w64-x86_64-toolchain

      - name: Build
        uses: ./.github/actions/build
        with:
          shell: msys2 {0}
